//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Training.Job.DAL.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public int TaskID { get; set; }
        public string TaskName { get; set; }
        public bool TaskProcessed { get; set; }
        public Nullable<int> TypeID { get; set; }
        public Nullable<System.DateTime> TaskDate { get; set; }
    
        public virtual TaskType TaskType { get; set; }
    }
}
