USE [master]
GO

/****** Object:  Database [Training]    Script Date: 5/10/2021 2:48:48 PM ******/
CREATE DATABASE [Training]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Training', FILENAME = N'D:\SqlData\Training.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Training_log', FILENAME = N'D:\SqlData\Training_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Training].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Training] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Training] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Training] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Training] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Training] SET ARITHABORT OFF 
GO

ALTER DATABASE [Training] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Training] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Training] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Training] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Training] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Training] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Training] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Training] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Training] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Training] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Training] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Training] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Training] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Training] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Training] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Training] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Training] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Training] SET RECOVERY FULL 
GO

ALTER DATABASE [Training] SET  MULTI_USER 
GO

ALTER DATABASE [Training] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Training] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Training] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Training] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Training] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Training] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Training] SET  READ_WRITE 
GO


USE [Training]
GO

/****** Object:  Table [dbo].[Tasks]    Script Date: 5/10/2021 2:49:28 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TaskTypes](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](50) NULL,
 CONSTRAINT [PK_TaskTypes] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[Tasks](
	[TaskID] [int] IDENTITY(1,1) NOT NULL,
	[TaskName] [varchar](50) NULL,
	[TaskProcessed] [bit] NOT NULL,
	[TypeID] [int] NULL,
	[TaskDate] [datetime] NULL,
 CONSTRAINT [PK_Tasks] PRIMARY KEY CLUSTERED 
(
	[TaskID] ASC
)
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Tasks] ADD  DEFAULT ((0)) FOR [TaskProcessed]
GO

ALTER TABLE [dbo].[Tasks]  WITH CHECK ADD FOREIGN KEY([TypeID])
REFERENCES [dbo].[TaskTypes] ([ID])
GO

CREATE NONCLUSTERED INDEX [IX_processed_date] ON [dbo].[Tasks]
(
	[TaskID] ASC,
	[TaskProcessed] ASC,
	[TaskDate] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO

--seed

  insert into TaskTypes values ('Notification'),('Job'),('File')
  
  insert into Tasks values ('Notification',0,1, GETDATE())
  insert into Tasks values ('Add Invoice File',0,3, '2021/05/12')
  insert into Tasks values ('Push to S3 Notification',0,1, '2021/05/13')
  insert into Tasks values ('Restore Database2',0,2, '2021/05/14')